- pkg:pypi/awslabs.prometheus-mcp-server@0.1.1
- pkg:pypi/awslabs.prometheus-mcp-server@0.2.1
- pkg:pypi/awslabs.prometheus-mcp-server@0.2.2
- pkg:pypi/awslabs.prometheus-mcp-server@0.2.3
- pkg:pypi/awslabs.prometheus-mcp-server@0.2.5
- pkg:pypi/awslabs.prometheus-mcp-server@0.2.6
- pkg:pypi/awslabs.prometheus-mcp-server@0.2.7
